version: '3.8'
services:
  myapp:
    build: .
    env_file:
      - .env  # Charge les variables d'environnement depuis .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}